name: Profile Metrics (Compact)

on:
  schedule:
    - cron: "15 7 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate compact metrics.svg
        uses: lowlighter/metrics@latest
        with:
          user: cyberbryanzhang
          filename: metrics.svg

          output_action: commit
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "chore(metrics): compact profile metrics [skip ci]"

          template: classic
          base: header
          config_timezone: America/Phoenix
          config_twemoji: yes

          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_ignored: html, css, scss

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_habits: no
          plugin_achievements: no
          plugin_traffic: no
          plugin_followup: no

          token: ${{ secrets.METRICS_TOKEN }}
